#Nicholas Fafel and Sohan Gadiraju
 
fewest: fewest.o
	g++ fewest.o -o fewest
 
fewest.o: fewest.cpp
	g++ -c fewest.cpp
 
different: different.o
	g++ different.o -o different
 
different.o: different.cpp
	g++ -c different.cpp
 
clean:
	rm *.o fewest different
